//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public abstract class Command
{
	protected Room room;
	public Command (Room room)
	{
		this.room = room;
	}

	public abstract void Undo ();
	public virtual void Execute(){

	}
}


