//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class DeleteFurnitureCommand : Command
{
	private string furnitureName;
	private string furnitureId;
	private Vector3 position;
	private Quaternion rotation;

	public DeleteFurnitureCommand (GameObject toDelete, Room room):base(room)
	{
		Furniture fc = toDelete.GetComponent<Furniture> ();
		furnitureId = fc.getFurnitureType().id;
		furnitureName = toDelete.name;
		position = toDelete.transform.localPosition;
		rotation = toDelete.transform.localRotation;
	}
	public override void Undo ()
	{
		GameObject toRecreate = Catalog.getCatalog ().createFurniture (furnitureId, 
		                                                           position, 
		                                                           -rotation.eulerAngles.y, false);
		room.addFurniture (toRecreate.GetComponent<Furniture> ());
		toRecreate.transform.localPosition = position;
		toRecreate.transform.localRotation = rotation;
		toRecreate.transform.parent = room.gameObject.transform;
		toRecreate.name = furnitureName;
	}
}


