//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class MoveFurnitureCommand : Command
{
	private String furnitureId;
	private Vector3 oldPosition;
	private Quaternion oldRotation;

	public MoveFurnitureCommand (GameObject oldF, Room room) : base(room)
	{
		oldPosition = oldF.transform.localPosition;
		oldRotation = oldF.transform.localRotation;
		this.furnitureId = oldF.name;
	}

	public override void Undo ()
	{
		foreach (Furniture f in room.furnitures) {
			if(f.gameObject.name.Equals(furnitureId)){
				f.transform.localPosition=oldPosition;
				f.transform.localRotation=oldRotation;
				return;
			}
		}
	}
}


