//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class SwapFurnitureCommand : Command
{
	string furnitureOldId;
	string furnitureOldName;
	Vector3 position;
	Quaternion rotation;

	public SwapFurnitureCommand (GameObject from, GameObject to, Room room) : base(room)
	{
		furnitureOldName = from.name;
		furnitureOldId = from.GetComponent<Furniture> ().getFurnitureType ().id;
		position = from.transform.localPosition;
		rotation = from.transform.localRotation;
	}
	public override void Undo ()
	{
		GameObject toDelete = null;
		Furniture toDeleteF = null;
		foreach (Furniture f in room.furnitures) {
			if(f.name.Equals(furnitureOldName)){
				toDelete = f.gameObject;
				toDeleteF = f;
				break;
			}
		}
		room.furnitures.Remove (toDeleteF);
		GameObject toAdd = Catalog.getCatalog ().createFurniture (furnitureOldId, position, 0);
		room.furnitures.Add (toAdd.GetComponent<Furniture> ());
		toAdd.name = furnitureOldName;
		toAdd.transform.parent = room.gameObject.transform;
		toAdd.transform.localPosition = position;
		toAdd.transform.localRotation = rotation;


		Debug.Log (toAdd.transform.localPosition);
		Debug.Log (toAdd.transform.localRotation);

		GameObject.Destroy (toDelete);
	}
}

